### ISSUE TITLE
Feedback on ciaopp installation

### ISSUE THREAD

**Issue by jeshan** [ciao-lang/typeslib#1]
> Not sure if I should raise this issue in this project or for ciaopp

Hi team,
I'm new to Prolog and eager to specifically try Ciao as it looks very exciting!
I wanted to get a full emacs setup and it was mostly straightforward. However, ciaopp was quite troublesome to install.

In particular, compilation failed to due to write_list1 not being found in the basic type operations file of this project:
https://github.com/ciao-lang/typeslib/blob/b57c5b005e60d93d59159144b3f199e4aba48be5/src/basic_type_operations.pl#L29-L31

I couldn't find a definition of it anywhere. I've changed it to "write" as a workaround.
Also, [its docs](https://cliplab.org/~clip/Software/Ciao/ciaopp-1.2.0.html/ciaopp_ref_manintro.html) say to:

> "Currently there are two Ciao distributions, one which includes CiaoPP, and another one which does not, For installing the Ciao distributions which include CiaoPP, it is sufficient to follow the instructions enclosed in the Ciao distribution itself"

That was where I got stuck as I did not what to do next.
Can you confirm if `./ciao-boot.sh get ciaopp` is the right way to get ciaopp?
That's the step that was pulling the code that couldn't compile.

I think fixing this will encourage people to try the Ciao system.

**Comment by igcontreras** [comment]
Hi, 

thanks for pointing this out.

`./ciao-boot.sh get ciaopp` is the correct way to get ciaopp. It should be fixed now.
